### ISSUE TITLE
Reporte entrevista 

### ISSUE THREAD

**Issue by Anakimberly** [SistemasTecTlaxiaco/actividad-7-practica-de-entrevista-equipo-v-a-k#1]
[Reporte Entrevista Usuarios  Loc-Serv.pdf](https://github.com/user-attachments/files/17623310/Reporte.Entrevista.Usuarios.Loc-Serv.pdf)

**Comment by edgarmauricio123** [comment]
Después de haber revisado con la rubrica cubre los requisitos por lo tanto tiene el 30%

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
